spring.application.name=votezy

spring.main.banner-mode=off

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=sopan
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.port=8088

#email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sopan1916000070@gmail.com
spring.mail.password=oxajbpiopnmzuide
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
